version: '3.5'
services:
  backend:
    build: ./Server
    ports:
      - "80:80"
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
      - "5006:5006"
    volumes:
      - ./:/usr/src/app